from _typeshed import Incomplete
from django_jsonform.constants import JOIN_SYMBOL as JOIN_SYMBOL

def normalize_schema(schema): ...
def normalize_keyword(kw): ...
def get_schema_type(schema): ...
def get_setting(name, default: Incomplete | None = ...): ...
def join_coords(*coords): ...
def split_coords(coords): ...

class ErrorMap(dict):
    def set(self, coords, msg) -> None: ...
    def append(self, coords, msg) -> None: ...
