from _typeshed import Incomplete
from django.db import models
from django_jsonform.forms.fields import JSONFormField as JSONFormField

class JSONField(models.TextField):
    encoder: Incomplete
    decoder: Incomplete
    def __init__(self, verbose_name: Incomplete | None = ..., name: Incomplete | None = ..., encoder: Incomplete | None = ..., decoder: Incomplete | None = ..., **kwargs) -> None: ...
    def deconstruct(self): ...
    def to_python(self, value): ...
    def from_db_value(self, value, expression, connection): ...
    def get_prep_value(self, value): ...
    def validate(self, value, model_instance) -> None: ...
    def value_to_string(self, obj): ...
    def formfield(self, **kwargs): ...
