from _typeshed import Incomplete
from django import forms

class JSONFormField(forms.CharField):
    default_error_messages: Incomplete
    encoder: Incomplete
    decoder: Incomplete
    def __init__(self, encoder: Incomplete | None = ..., decoder: Incomplete | None = ..., **kwargs) -> None: ...
    def to_python(self, value): ...
    def bound_data(self, data, initial): ...
    def prepare_value(self, value): ...
    def has_changed(self, initial, data): ...

class InvalidJSONInput(str): ...
class JSONString(str): ...
